### ISSUE TITLE
Add social preview cards to crossplane.io

### ISSUE THREAD

**Issue by bassam** [crossplane/website#14]
I'm not seeing them
<img width="1066" alt="CleanShot 2022-12-01 at 12 40 32@2x" src="https://user-images.githubusercontent.com/1463491/205155082-8b089151-429a-448a-afa6-77b868f0ba8a.png">

**Comment by plumbis** [comment]
Related to #12

**Comment by nicoleblom** [comment]
@bassam @plumbis Fixed in #12
Tested en confirmed on https://unomena.atlassian.net/browse/UP-208
