### ISSUE TITLE
Slack invite link down (heroku issue?)

### ISSUE THREAD

**Issue by aslom** [crossplane/website#37]
http://slack.crossplane.io/

<img width="813" alt="image" src="https://user-images.githubusercontent.com/1648338/226420725-e971e478-f985-4bc3-877f-ae3ba6b60c1c.png">

via https://docs.crossplane.io/v1.11/getting-started/

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1648338/226421062-3330bfe3-df6a-4c6c-927c-b018472bea11.png">

https://github.com/crossplane/website/blob/df8b7b1918b24939d560109277ec87366c0057d4/src/routes.ts

**Comment by jbw976** [comment]
Thanks for reporting this @aslom, we noticed this last week and we're investigating into how to fix the underlying issue.  You can follow along with the action over on https://github.com/crossplane/crossplane/issues/3872. 

Let us know if you have any suggestions there 😂  - I'll go ahead and close this one, so we can keep tracking in one place.  Thanks again @aslom!! 🙇‍♂️
