### ISSUE TITLE
How to add our company logo to the slack community logos in the homepage 

### ISSUE THREAD

**Issue by tossmilestone** [crossplane/website#64]
Hi, I'm a software engineer from Alauda. We have used Crossplane to simplify application deployment and infrastructure provisioning for our customers. I hope to add our company logo to your homepage as below. Please tell me what should I do to add the logo.

Thanks!

**Comment by jbw976** [comment]
Right on @tossmilestone, thanks for https://github.com/crossplane/crossplane/pull/6134 as well! We got an email from someone else on your team for this same request, so I'll try to get us all coordinated together 🙇‍♂️
